spring:
  datasource:
    url: jdbc:oracle:thin:@//10.0.1.255:1521/helowin
    username: scott
    password: lp123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5


mybatis:
  mapper-locations: mapper/*.xml
